name = "itty-hydra-demo"
workers_dev = true
main = "dist/index.mjs"

compatibility_date = "2023-10-10"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
    { binding = "HYDRA_ITTY_DEMO_KV", id = "b705fe111bf04913ab9a8b13b5a54844" }
]

[durable_objects]
bindings = [
  { name = "HydraRateLimiter", class_name = "HydraRateLimiter" }
]

[[migrations]]
tag = "v1"
new_classes = ["HydraRateLimiter"]

[build]
command = "npm run build"

[dev]
ip = "0.0.0.0"
local_protocol="http"
upstream_protocol="https"