name = "itty-hydra-demo"
workers_dev = true
main = "dist/index.mjs"

compatibility_date = "2023-10-10"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
    { binding = "HYDRA_ACME", id = "c63f48a0f29843e8ab8251ef533e1c9c" }    
]

[durable_objects]
bindings = [
  { name = "HydraRateLimiter", class_name = "HydraRateLimiter" }
]

[[migrations]]
tag = "v1"
new_classes = ["HydraRateLimiter"]

[build]
command = "npm run build"

[dev]
ip = "0.0.0.0"
local_protocol="http"
upstream_protocol="https"